App_Inicio/urls.py
from django import urls
from django.urls import path
from . import views

app_name = "App_Inicio"

urlpatterns = [
    path('', views.index, name='index'),
    path('acercade', views.acercade, name='acercade'),
    path('nuevoproducto', views.nuevoproducto, name='nuevoproducto'),
    path('editar/<int:id>', views.editar_producto, name='editar-producto'),
    path('register', views.register_request, name="register"),
    path('login', views.login_request, name="login"),
    path('logout', views.logout_request, name= "logout"),
    path('detalle/<int:id>', views.detalleproducto, name='detalleproducto'),
    path('categoria/<int:categoria>', views.categorias_filtro, name='categoria'),
    path('busqueda/', views.busqueda, name='resultado_busqueda'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove-from-cart'),
    path('reduce-from-cart/<int:id>/', views.reduce_quantity_item, name='reduce-from-cart'),
    path('clean-cart/', views.clean_cart, name='clean-cart'),
    path('carrito/', views.carrito, name='carrito'),
    path('finalizar-compra/', views.finalizar_compra, name='finalizar-compra'),
]

JAGUARETE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App_Inicio.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

App_Inicio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categorias(models.Model):
    descripcion = models.CharField(max_length=64)
    def __str__(self):
        return self.descripcion

class Producto(models.Model):
    titulo = models.CharField(max_length=64)
    imagen = models.ImageField(upload_to="images")
    descripcion = models.CharField(max_length=1500, blank = True)
    precio = models.DecimalField(max_digits = 50, decimal_places = 2)
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.titulo} de la categoria {self.categoria}"

class ProductoCarrito(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item  = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.titulo}"

    def get_total_item_price(self):
        return self.quantity * self.item.precio

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(ProductoCarrito)
    precio = models.DecimalField(max_digits = 999999, decimal_places = 2, default=0)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.usuario.username} y {self.items.count()}"
    
    def get_total_items(self):
        totalitems = 0
        for order_item in self.items.all():
            totalitems += order_item.quantity
        return totalitems

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

class Nivel(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    experiencia = models.DecimalField(max_digits = 999999, decimal_places = 2, default=0)

    def __str__(self):
        return f"{self.usuario.username} tiene {self.experiencia} puntos de experiencia!"

    def get_user_level(self):
        levels = [15000, 37500, 80000, 150000, 400000, 750000, 1250000, 2000000, 3500000, 5000000]
        lvl = len([x for x in levels if self.experiencia > x])
        return lvl

    def get_user_percentage(self):
        levels = [15000, 37500, 80000, 150000, 400000, 750000, 1250000, 2000000, 3500000, 5000000]
        lvl = len([x for x in levels if self.experiencia > x])
        if lvl == 10:
            get_experience = 100
        else:
            if lvl == 0:
                dif_experiencia = levels[lvl]
                get_experience = self.experiencia / dif_experiencia * 100
            else:
                dif_experiencia = levels[lvl] - levels[lvl - 1]
                get_experience = (self.experiencia - levels[lvl - 1]) / dif_experiencia * 100
        get_experience_int = int(get_experience)
        return get_experience_int

    def get_user_exp(self):
        levels = [15000, 37500, 80000, 150000, 400000, 750000, 1250000, 2000000, 3500000, 5000000]
        lvl = len([x for x in levels if self.experiencia > x])
        if lvl == 0:
            dif_experiencia = levels[lvl]
            get_experience = dif_experiencia - self.experiencia
        else:
            dif_experiencia = levels[lvl] - levels[lvl - 1]
            get_experience = (self.experiencia - levels[lvl - 1]) - dif_experiencia
        get_experience_int = int(get_experience)
        return get_experience_int

App_Inicio/forms.py
from django.forms.models import ModelForm
from App_Inicio.models import Producto
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

#alta de producto
class FormNuevoProducto(ModelForm):
    class Meta:
        model = Producto
        fields = ['titulo', 'imagen', 'descripcion', 'precio', 'categoria']
        exclude = ['title']
    descripcion = forms.CharField(widget= forms.Textarea, label="body",required=True)

App_Inicio/views.py
from django.contrib.auth import login, authenticate, logout
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from .forms import FormNuevoProducto, NewUserForm
from django.contrib import messages
from .models import Carrito, Categorias, Producto, ProductoCarrito, Nivel
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def index(request):
	ultimosTres = Producto.objects.all().order_by('-id')[:3]
	ultimosDiez = Producto.objects.all().order_by('-id')[3:10]
	return render(request, 'web/inicio.html', context={'ultimosTres': ultimosTres, 'ultimosDiez': ultimosDiez})

def acercade(request):
    return render(request, 'web/acercade.html')
    
@login_required(login_url='App_Inicio:register')
def nuevoproducto(request):
    form = FormNuevoProducto(request.POST, request.FILES)

    if form.is_valid():
        form.save()
        messages.success(request, "Producto agregado exitosamente!" )

    return render(request, 'web/nuevoproducto.html', {
        "form": FormNuevoProducto()
    })

@login_required(login_url='App_Inicio:register')
def editar_producto(request, id):
    instance = get_object_or_404(Producto, id=id)
    form = FormNuevoProducto(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        messages.success(request, "Producto editado exitosamente!" )
    return render(request, 'web/editarproducto.html', {"form": form, "id":id})

#registro de usuarios
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            Nivel(usuario=user).save()
            Carrito(usuario=user).save()
            return redirect("/")
        messages.error(request, "El registro contiene información invalida.")
    form = NewUserForm
    return render (request=request, template_name="web/register.html", context={"register_form":form})

#login de usuario
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect("/")
			else:
				messages.error(request,"Nombre de usuario o contraseña incorrectos.")
		else:
			messages.error(request,"Nombre de usuario o contraseña incorrectos.")
	form = AuthenticationForm()
	return render(request=request, template_name="web/login.html", context={"login_form":form})

@login_required(login_url='App_Inicio:register')
def logout_request(request):
	logout(request)
	return redirect("/")

def detalleproducto(request, id):
	producto = Producto.objects.get(id=id)
	context = {'producto': producto}
	return render(request, 'web/detalle.html', context)

def categorias_filtro(request, categoria):
	productoscat = Producto.objects.filter(categoria=categoria).order_by('-id')
	productoscantidad = Producto.objects.filter(categoria=categoria).count()
	categoriatitle = Categorias.objects.get(id=categoria)
	paginator = Paginator(productoscat, 5)
	numero_pagina = request.GET.get('page')
	categoria_pag = paginator.get_page(numero_pagina)
	context = {'categoria_pag': categoria_pag, 'categoriatitle':categoriatitle, 'productoscantidad': productoscantidad}
	return render(request, 'web/categoria.html', context)

def busqueda(request):
    busqueda = request.GET.get('query')
    productos = Producto.objects.filter(Q(titulo__icontains=busqueda) | Q(descripcion__icontains=busqueda) | Q(categoria__descripcion__icontains=busqueda))
    context = {'productobusqueda': productos, 'busqueda':busqueda}
    return render(request, 'web/resultados.html', context)

@login_required(login_url='App_Inicio:register')
def add_to_cart(request, id):
    item = get_object_or_404(Producto, id=id)
    order_item, created = ProductoCarrito.objects.get_or_create(
        item = item,
        user = request.user,
        ordered = False
    )
    order_qs = Carrito.objects.filter(usuario=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__id=item.id).exists():
            order_item.quantity += 1
            order_item.save()
            order_quantity = order.get_total_items()
            return HttpResponse(order_quantity)
        else:
            order.items.add(order_item)
            order_quantity = order.get_total_items()
            return HttpResponse(order_quantity)
    else:
        order = Carrito.objects.create(usuario=request.user)
        order.items.add(order_item)
        order_quantity = order.get_total_items()
        return HttpResponse(order_quantity)

@login_required(login_url='App_Inicio:register')
def remove_from_cart(request, id):
    item = get_object_or_404(Producto, id=id )
    order_qs = Carrito.objects.filter(
        usuario=request.user, 
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item = ProductoCarrito.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order_item.delete()
            return redirect("App_Inicio:carrito")
        else:
            return redirect("App_Inicio:carrito")
    else:
        return redirect("App_Inicio:carrito")

@login_required(login_url='/accounts/login/')
def reduce_quantity_item(request, id):
    item = get_object_or_404(Producto, id=id )
    order_qs = Carrito.objects.filter(
        usuario = request.user, 
        ordered = False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists() :
            order_item = ProductoCarrito.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()
            return redirect("App_Inicio:carrito")
        else:
            return redirect("App_Inicio:carrito")
    else:
        return redirect("App_Inicio:carrito")

@login_required(login_url='App_Inicio:register')
def clean_cart(request):
    order = Carrito.objects.get(usuario=request.user, ordered=False)
    order_items = order.items.all()
    for item in order_items:
        item.delete()
        order.save()
    return redirect("App_Inicio:carrito")

@login_required(login_url='App_Inicio:register')
def carrito(request):
    order = Carrito.objects.get(usuario=request.user, ordered=False)
    finalorder = order.items.all()
    quantity = finalorder.count()
    if quantity == 0:
        products = False
    else:
        products = True
    nivel = Nivel.objects.get(usuario=request.user)
    get_descuentopercentage = nivel.get_user_level() / 100
    precioparcial = order.get_total_price()
    get_descuento = float(precioparcial) * float(get_descuentopercentage)
    preciofinal = float(precioparcial) - get_descuento
    context = {'finalorder' : finalorder, 'preciofinal': preciofinal, 'products': products, 'get_descuento':get_descuento, 'precioparcial': precioparcial}
    return render(request, 'web/carrito.html', context)

@login_required(login_url='App_Inicio:register')
def finalizar_compra(request):
    userlvlmodel = Nivel.objects.get(usuario=request.user)
    order = Carrito.objects.get(usuario=request.user, ordered=False)
    preciofinal = order.get_total_price()
    userlvlmodel.experiencia += preciofinal
    order_items = order.items.all()
    for item in order_items:
        item.delete()
        order.save()
    userlvlmodel.save()
    return redirect("App_Inicio:carrito")

App_Inicio/templates/web/acercade.html
{% extends 'web/layout.html' %}
{% load static %}

{% block title %} Acerca de {% endblock %}

{% block article_section %}

<h1 class="acercadeTitle">Acerca de Jaguarete KAA</h1>

<div class="contenidoacerca">
<p class="descripcion">Jaguarete KAA es un eCommerce nacional que te lleva todos los productos a tu puerta.<br> 
Reúne los miles de productos de las tiendas más grandes del pais y permite pagar en pesos y hasta en 12 cuotas fijas.<br>
Llevamos más de <b>5 años</b> en el mercado con muy buenas referencias por parte de nuestros clientes!</p>

<div class="pqcomprar">
    <h3>¿Por qué comprar en Jaguarete KAA?</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Tenés variedad.</li>
        <li class="list-group-item">Encontrás disponibilidad.</li>
        <li class="list-group-item">Pagás en pesos y con hasta 12 cuotas fijas</li>
        <li class="list-group-item">Tus compras están aseguradas y tienen garantía de entrega</li>
        <li class="list-group-item">Ves el precio final al momento de pagar. ¡Sin sorpresas!</li>
    </ul>
</div>

<div class="container">
    <div class="row">
      <div class="col-sm reporteEmpresa">
        <p class="textocontenido"><b>+500</b> nuevos clientes cada mes</p>
      </div>
      <div class="col-sm reporteEmpresa">
        <p class="textocontenido"><b>+100.000</b> clientes totales</p>
      </div>
      <div class="col-sm reporteEmpresa">
        <p class="textocontenido"><b>19857</b> productos distintos</p>
      </div>
      <div class="col-sm reporteEmpresa">
        <p class="textocontenido"><b>875</b> envios cada més</p>
      </div>
    </div>
</div>

</div>



{% endblock %}

App_Inicio/templates/web/carrito.html
{% extends 'web/layout.html' %}
{% load static %}

{% block title %} Carrito de compras {% endblock %}

{% block article_section %}

<div>
<div class="carrito bg-light m-3 p-3 mx-auto" id="carrito1">
    <h1 class="mx-auto text-center display-4">Carrito</h1>

    <ul>
    {% for n in finalorder %}
        <div class="border-top border-bottom p-3">
            <li>
                <div class="d-flex flex-row justify-content-md-between p-1">
                    <div class="d-flex flex-row">
                        <img src="{{ n.item.imagen.url}}" class="img-fluid img-thumbnail imagencarrito mx-auto" alt="Producto">
                        <div class="d-flex flex-column p-2 contenedorcarrito2">
                            <h4>{{ n.item.titulo }}</h4>
                            <span class="" style="color:gray">Cantidad de productos: {{ n.quantity }} <a type="button" class="btn btn-secondary btn-sm" href="/reduce-from-cart/{{ n.item.id }}"><i style="font-size:12px" class="fa">&#xf149;</i></a></span>
                            <a href="/remove-from-cart/{{ n.item.id }}">Eliminar producto</a>
                        </div>
                    </div>
                    <div class="d-flex flex-column">
                        <h4 class="precioprodcarrito">${% widthratio n.item.precio 1 n.quantity %}</h4>
                    </div>
                </div>
            </li>
        </div>
    {% endfor %}
    </ul>
    <div class="d-flex justify-content-between">
        <a type="button" class="btn btn-danger align-self-center {% if products %}{% else %}disabled{% endif %}" href="{% url 'App_Inicio:clean-cart' %}">Limpiar Carrito</a>
        <div class="d-flex flex-column">
            <span>Precio parcial: ${{ precioparcial }}</span>
            <span style="color:#428331">Descuento por nivel: ${{ get_descuento|floatformat:2 }}</span>
            <span class="display-4 preciofincarrito">Precio total: ${{ preciofinal|floatformat:2 }}</span>
            <a type="button" onclick='AjaxComprar("/finalizar-compra/")' class="btn btn-primary {% if products %}{% else %}disabled{% endif %}">Finalizar compra</a>
        </div>
    </div>
</div>

<div class="carrito bg-light m-3 p-3 mx-auto" id="carrito2">
    <h1 class="mx-auto text-center display-4">Muchas gracias por su compra!</h1>
    <span class="mx-auto text-center">Usted ha obtenido <span style="color: green"><b>{{ precioparcial }}</b></span> puntos de experiencia con esta ultima compra!</span>
</div>
</div>

{% endblock %}

App_Inicio/templates/web/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'styles/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" />
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
    <title>Jaguarete KAA - {% block title %} {% endblock %}</title>
</head>

<header class="sticky-top">
    <nav class="navbar justify-content-center navbar-dark bg-dark navbar-expand-lg barra">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center titulo" href="/"> <img src="{% static 'images/logo.png' %}" alt="" width="40" height="40" class="d-inline-block align-text-top mx-2 logo"> <span class="marca">Jaguarete KAA</span>
                </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse flex-column align-items-end" id="navbarNavDropdown">
                <ul class="navbar-nav">

                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <div class="container usuario">
                      <div class="btnuser">
                        {% if request.user.is_staff %}
                        <div class="d-flex flex-column">
                          <span>Bienvenido <b>{{ user.get_username }}!</b></span>
                          <span class="badge bg-success">MODERADOR</span>
                        </div>
                        {% else %}
                        Bienvenido <b>{{ user.get_username }}!</b> <span class="badge bg-primary">Lvl. {{ userlvl }}</span>
                        <span class="visually-hidden">level</span>
                      <div class="progress progreso">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bg-success barranivel" role="progressbar" style="width: {{ userexppercentage }}%" aria-valuenow="{{ userexppercentage }}" aria-valuemin="0" aria-valuemax="100"><b>{{ userexppercentage }}%</b></div>
                      </div>
                      {% endif %}
                      </div>
                    </div>
                  </li>
                  {% endif %}
                  
                  {% if user.is_authenticated %}
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link ingresar" href="{% url 'App_Inicio:login' %}">Ingresar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link register" href="{% url 'App_Inicio:register' %}">Registro</a>
                  </li>

                  {% endif %}
            
                  {% if user.is_authenticated %}
                  {% if request.user.is_staff %}
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link cart" href="{% url 'App_Inicio:carrito' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>    <span class="badge bg-primary" id="carritospan">{{ productoscarrito }}</span></a>
                  </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link salir" href="{% url 'App_Inicio:logout' %}">Salir</a>
                  </li>
                  
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>

  <nav class="navbar navbar-expand-lg navbar-light bg-light menu">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link navmenu2 {% if request.resolver_match.url_name == 'index' %}menuactive2{% endif %}" href="/">Inicio</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle navmenu2 {% if request.resolver_match.url_name == 'categoria' %}menuactive2{% endif %}" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categorias
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                {% for n in categorias %}
                <li><a class="dropdown-item" href="/categoria/{{ n.id }}">{{ n.descripcion }}</a></li>
                {% endfor %}
              </ul>
            </li>
            <li class="nav-item"><a class="nav-link navmenu2 {% if request.resolver_match.url_name == 'acercade' %}menuactive2{% endif %}" href="{% url 'App_Inicio:acercade' %}">Acerca de</a></li>
            <li class="nav-item"><a class="nav-link navmenu2" href="mailto:santi.cappelletti@gmail.com">Contacto</a></li>
            {% if request.user.is_staff %}
            <li class="na-item"><a class="nav-link navmenu2 {% if request.resolver_match.url_name == 'nuevoproducto' %}menuactive2{% endif %}" href="{% url 'App_Inicio:nuevoproducto' %}"> + Nuevo producto</a></li>
            {% endif %}
          </ul>
          <form class="form-inline" action="{% url 'App_Inicio:resultado_busqueda' %}" method="get">
            <input class="align-middle" type="search" placeholder="Inserte una palabra..." aria-label="Buscar" input name="query">
            <button class="btn btn-outline-success btn-sm align-middle" type="submit">Buscar</button>
          </form>
      </div>
  </nav>
</header>

<body>
  {% block article_section %}{% endblock article_section %}
</body>

<div class="position-fixed bottom-0 start-0 p-3" style="z-index: 11">
  <div id="liveToast" class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="1000">
    <div class="d-flex">
      <div class="toast-body">
        Producto agregado al carrito!
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>

<footer class="page-footer font-small bg-dark">
    <div class="footer-copyright text-center py-3">© 2021 JAGUARETE KAA S.A. Todos los derechos reservados / Desarrollo web por Santiago Cappelletti</div>
</footer>

</html>

App_Inicio/templates/web/nuevoproducto.html
{% extends 'web/layout.html' %}
{% load static %}

{% block title %} Nuevo producto {% endblock %}

{% block article_section %}

{% if request.user.is_staff %}

<h1 id="nuevoprodtit">Agregar un nuevo producto:</h1>

<div class="w-100 contenedoragregar bg-light">

  <form action="{% url 'App_Inicio:nuevoproducto' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.management_form }}
    <div class="nuevoproducto bg-secondary">
      <ul>
          <li><label>Título del producto: </label></li>
          <li>{{ form.titulo }}</li>
          <li><label>Imagen del producto: </label></li>
          <li>{{ form.imagen }}</li>
          <li><label>Descripción del producto: </label></li>
          <li>{{ form.descripcion }}</li>
          <li><label>Precio del producto: </label></li>
          <li>{{ form.precio }}</li>
          <li><label>Categoria: </label></li>
          <li>{{ form.categoria }}</li>
          <li><button class="btn btn-primary" type="submit">Guardar!</button></li>
      </ul>
      {% if messages %}
				<div class="alert alert-success alert-dismissible fade show" role="alert">
					<ul class="messages">
						{% for message in messages %}
						<li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
						{% endfor %}
					</ul>
					
					<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			  	</div>
		{% endif %}
    </div>
  </form>
</div>

{% else %}
<h1>No tiene permisos para acceder a este sitio.</h1>

{% endif %}

{% endblock %}